<?php

use CRM_Payment2c2p_ExtensionUtil as E;

class CRM_Payment2c2p_Config
{
    const PAYMENT_2C2P_VERSION = '8.5'; //Current version used for 2c2p integration.
    const PAYMENT_2C2P_DEFAULT_LANG = 'en_GB'; //Payment getaway default langauge supported.
    const PAYMENT_RESPONCE = array(
        "0000" => "Successful",
        "0001" => "Transaction is pending", // Pending
        "0003" => "Transaction is cancelled",
        "0999" => "System error",
        "2001" => "Transaction in progress", //In Progress
        "2002" => "Transaction not found",
        "2003" => "Failed To Inquiry",
        "4001" => "Refer to card issuer",
        "4002" => "Refer to issuer's special conditions",
        "4003" => "Invalid merchant ID",
        "4004" => "Pick up card",
        "4005" => "Do not honor",
        "4006" => "Error",
        "4007" => "Pick up card, special condition",
        "4008" => "Honor with ID",
        "4009" => "Request in progress",
        "4010" => "Partial amount approved",
        "4011" => "Approved VIP",
        "4012" => "Invalid Transaction",
        "4013" => "Invalid Amount",
        "4014" => "Invalid Card Number",
        "4015" => "No such issuer",
        "4016" => "Approved, Update Track 3",
        "4017" => "Customer Cancellation",
        "4018" => "Customer Dispute",
        "4019" => "Re-enter Transaction",
        "4020" => "Invalid Response",
        "4021" => "No Action Taken",
        "4022" => "Suspected Malfunction",
        "4023" => "Unacceptable Transaction Fee",
        "4024" => "File Update Not Supported by Receiver",
        "4025" => "Unable to Locate Record on File",
        "4026" => "Duplicate File Update Record",
        "4027" => "File Update Field Edit Error",
        "4028" => "File Update File Locked Out",
        "4029" => "File Update not Successful",
        "4030" => "Format Error",
        "4031" => "Bank Not Supported by Switch",
        "4032" => "Completed Partially",
        "4033" => "Expired Card - Pick Up",
        "4034" => "Suspected Fraud - Pick Up",
        "4035" => "Restricted Card - Pick Up",
        "4036" => "Allowable PIN Tries Exceeded",
        "4037" => "No Credit Account",
        "4038" => "Allowable PIN Tries Exceeded",
        "4039" => "No Credit Account",
        "4040" => "Requested Function not Supported",
        "4041" => "Lost Card - Pick Up",
        "4042" => "No Universal Amount",
        "4043" => "Stolen Card - Pick Up",
        "4044" => "No Investment Account",
        "4045" => "Settlement Success",
        "4046" => "Settlement Fail",
        "4047" => "Cancel Success",
        "4048" => "Cancel Fail",
        "4049" => "No Transaction Reference Number",
        "4050" => "Host Down",
        "4051" => "Insufficient Funds",
        "4052" => "No Cheque Account",
        "4053" => "No Savings Account",
        "4054" => "Expired Card",
        "4055" => "Incorrect PIN",
        "4056" => "No Card Record",
        "4057" => "Transaction Not Permitted to Cardholder",
        "4058" => "Transaction Not Permitted to Terminal",
        "4059" => "Suspected Fraud",
        "4060" => "Card Acceptor Contact Acquirer",
        "4061" => "Exceeds Withdrawal Amount Limits",
        "4062" => "Restricted Card",
        "4063" => "Security Violation",
        "4064" => "Original Amount Incorrect",
        "4065" => "Exceeds Withdrawal Frequency Limit",
        "4066" => "Card Acceptor Call Acquirer Security",
        "4067" => "Hard Capture - Pick Up Card at ATM",
        "4068" => "Response Received Too Late",
        "4069" => "Reserved",
        "4070" => "Settle amount cannot exceed authorized amount",
        "4071" => "Inquiry Record Not Exist",
        "4072" => "Promotion not allowed in current payment method",
        "4073" => "Promotion Limit Reached",
        "4074" => "Reserved",
        "4075" => "Allowable PIN Tries Exceeded",
        "4076" => "Invalid Credit Card Format",
        "4077" => "Invalid Expiry Date Format",
        "4078" => "Invalid Three Digits Format",
        "4079" => "Reserved",
        "4080" => "User Cancellation by Closing Internet Browser",
        "4081" => "Unable to Authenticate Card Holder",
        "4082" => "Reserved",
        "4083" => "Reserved",
        "4084" => "Reserved",
        "4085" => "Reserved",
        "4086" => "ATM Malfunction",
        "4087" => "No Envelope Inserted",
        "4088" => "Unable to Dispense",
        "4089" => "Administration Error",
        "4090" => "Cut-off in Progress",
        "4091" => "Issuer or Switch is Inoperative",
        "4092" => "Financial Insititution Not Found",
        "4093" => "Trans Cannot Be Completed",
        "4094" => "Duplicate Transmission",
        "4095" => "Reconcile Error",
        "4096" => "System Malfunction",
        "4097" => "Reconciliation Totals Reset",
        "4098" => "MAC Error",
        "4099" => "Unable to Complete Payment",
        "4110" => "Settled",
        "4120" => "Refunded",
        "4121" => "Refund Rejected",
        "4122" => "Refund Failed",
        "4130" => "Chargeback",
        "4131" => "Chargeback Rejected",
        "4132" => "Chargeback Failed",
        "4140" => "Transaction Does Not Exist",
        "4200" => "Tokenization Successful",
        "4201" => "Tokenization Failed",
        "5002" => "Timeout",
        "5003" => "Invalid Message",
        "5004" => "Invalid Profile (Merchant) ID",
        "5005" => "Duplicated Invoice",
        "5006" => "Invalid Amount",
        "5007" => "Insufficient Balance",
        "5008" => "Invalid Currency Code",
        "5009" => "Payment Expired",
        "5010" => "Payment Canceled By Payer",
        "5011" => "Invalid Payee ID",
        "5012" => "Invalid Customer ID",
        "5013" => "Account Does Not Exist",
        "5014" => "Authentication Failed",
        "5015" => "Customer paid more than transaction amount",
        "5016" => "Customer paid less than transaction amount",
        "5017" => "Paid Expired",
        "5018" => "Reserved",
        "5019" => "No-Action From WebPay",
        "5998" => "Internal Error",
        "6012" => "Invalid Transaction",
        "6101" => "Invalid request message",
        "6102" => "Required Payload",
        "6103" => "Invalid JWT data",
        "6104" => "Required merchantId",
        "6105" => "Required paymentChannel",
        "6106" => "Required authCode",
        "6107" => "Invalid merchantId",
        "6108" => "Invalid paymentChannel",
        "6109" => "paymentChannel is not configured",
        "6110" => "Unable to retrieve usertoken",
        "7012" => "Invalid Transaction",
        "9004" => "The value is not valid",
        "9005" => "Some mandatory fields are missing",
        "9006" => "This field exceeded its authorized length",
        "9007" => "Invalid merchant",
        "9008" => "Invalid payment expiry",
        "9009" => "Amount is invalid",
        "9010" => "Invalid Currency Code",
        "9012" => "paymentItem name is required",
        "9013" => "paymentItem quantity is required",
        "9014" => "paymentItem amount is required",
        "9015" => "Existing Invoice Number",
        "9035" => "Payment failed",
        "9037" => "Merchant configuration is missing",
        "9038" => "Failed To Generate Token",
        "9039" => "The merchant frontend URL is missing",
        "9040" => "The token is invalid",
        "9041" => "Payment token already used",
        "9042" => "Hash value mismatch",
        "9057" => "Payment options are invalid",
        "9058" => "Payment channel invalid",
        "9059" => "Payment channel unauthorized",
        "9060" => "Payment channel unconfigured",
        "9078" => "Promotion code does not exist",
        "9080" => "Tokenization not allowed",
        "9088" => "SubMerchant is required",
        "9089" => "Duplicated SubMerchant",
        "9090" => "SubMerchant Not Found",
        "9091" => "Invalid Sub Merchant ID",
        "9092" => "Invalid Sub Merchant invoiceNo",
        "9093" => "Existing Sub Merchant Invoice Number",
        "9094" => "Invalid Sub Merchant Amount",
        "9095" => "Sub Merchant Amount mismatch",
        "9901" => "Invalid invoicePrefix",
        "9902" => "allowAccumulate is required",
        "9903" => "maxAccumulateAmount is required",
        "9904" => "recurringInterval or ChargeOnDate is required",
        "9905" => "recurringCount is required",
        "9906" => "recurringInterval or ChargeOnDate is required",
        "9907" => "Invalid ChargeNextDate",
        "9908" => "Invalid ChargeOnDate",
        "9909" => "chargeNextDate is required",
        "9990" => "Request to merchant front end has failed",
        "9991" => "Request merchant secure has failed",
        "9992" => "Request payment secure has failed",
        "9993" => "An unknown error has occured",
        "9994" => "Request DB service has failed",
        "9995" => "Request payment service has failed",
        "9996" => "Request Qwik service has failed",
        "9997" => "Request user preferences has failed",
        "9998" => "Request store card has failed",
        "9999" => "Request to merchant backend has failed"
    );

    public static function write_log($input, $ids, $preffix_log)
    {
        $redsys_settings = CRM_Core_BAO_Setting::getItem("Payment2c2p Settings", 'payment2c2p_settings');
        if ($redsys_settings['save_log'] == '1') {
            $masquerade_input = $input;
            $fields_to_hide = ['Ds_MerchantParameters', 'Ds_Signature', 'Ds_Merchant_Identifier'];
            foreach ($fields_to_hide as $field_to_hide) {
                unset($masquerade_input[$field_to_hide]);
            }
            Civi::log()->debug($preffix_log . print_r($masquerade_input, TRUE) . "\n ids: " . print_r($ids, TRUE));
        }
    }

    public function get_currency_code()
    {
        return array(
            "CLF" => array("Num" => "990", "exponent" => "4",),
            "BHD" => array("Num" => "048", "exponent" => "3",),
            "IQD" => array("Num" => "368", "exponent" => "3",),
            "JOD" => array("Num" => "400", "exponent" => "3",),
            "KWD" => array("Num" => "414", "exponent" => "3",),
            "LYD" => array("Num" => "434", "exponent" => "3",),
            "OMR" => array("Num" => "512", "exponent" => "3",),
            "TND" => array("Num" => "788", "exponent" => "3",),
            "AED" => array("Num" => "784", "exponent" => "2",),
            "AFN" => array("Num" => "971", "exponent" => "2",),
            "ALL" => array("Num" => "008", "exponent" => "2",),
            "AMD" => array("Num" => "051", "exponent" => "2",),
            "ANG" => array("Num" => "532", "exponent" => "2",),
            "AOA" => array("Num" => "973", "exponent" => "2",),
            "ARS" => array("Num" => "032", "exponent" => "2",),
            "AUD" => array("Num" => "036", "exponent" => "2",),
            "AWG" => array("Num" => "533", "exponent" => "2",),
            "AZN" => array("Num" => "944", "exponent" => "2",),
            "BAM" => array("Num" => "977", "exponent" => "2",),
            "BBD" => array("Num" => "052", "exponent" => "2",),
            "BDT" => array("Num" => "050", "exponent" => "2",),
            "BGN" => array("Num" => "975", "exponent" => "2",),
            "BMD" => array("Num" => "060", "exponent" => "2",),
            "BND" => array("Num" => "096", "exponent" => "2",),
            "BOB" => array("Num" => "068", "exponent" => "2",),
            "BOV" => array("Num" => "984", "exponent" => "2",),
            "BRL" => array("Num" => "986", "exponent" => "2",),
            "BSD" => array("Num" => "044", "exponent" => "2",),
            "BTN" => array("Num" => "064", "exponent" => "2",),
            "BWP" => array("Num" => "072", "exponent" => "2",),
            "BYN" => array("Num" => "933", "exponent" => "2",),
            "BZD" => array("Num" => "084", "exponent" => "2",),
            "CAD" => array("Num" => "124", "exponent" => "2",),
            "CDF" => array("Num" => "976", "exponent" => "2",),
            "CHE" => array("Num" => "947", "exponent" => "2",),
            "CHF" => array("Num" => "756", "exponent" => "2",),
            "CHW" => array("Num" => "948", "exponent" => "2",),
            "CNY" => array("Num" => "156", "exponent" => "2",),
            "COP" => array("Num" => "170", "exponent" => "2",),
            "COU" => array("Num" => "970", "exponent" => "2",),
            "CRC" => array("Num" => "188", "exponent" => "2",),
            "CUC" => array("Num" => "931", "exponent" => "2",),
            "CUP" => array("Num" => "192", "exponent" => "2",),
            "CZK" => array("Num" => "203", "exponent" => "2",),
            "DKK" => array("Num" => "208", "exponent" => "2",),
            "DOP" => array("Num" => "214", "exponent" => "2",),
            "DZD" => array("Num" => "012", "exponent" => "2",),
            "EGP" => array("Num" => "818", "exponent" => "2",),
            "ERN" => array("Num" => "232", "exponent" => "2",),
            "ETB" => array("Num" => "230", "exponent" => "2",),
            "EUR" => array("Num" => "978", "exponent" => "2",),
            "FJD" => array("Num" => "242", "exponent" => "2",),
            "FKP" => array("Num" => "238", "exponent" => "2",),
            "GBP" => array("Num" => "826", "exponent" => "2",),
            "GEL" => array("Num" => "981", "exponent" => "2",),
            "GHS" => array("Num" => "936", "exponent" => "2",),
            "GIP" => array("Num" => "292", "exponent" => "2",),
            "GMD" => array("Num" => "270", "exponent" => "2",),
            "GTQ" => array("Num" => "320", "exponent" => "2",),
            "GYD" => array("Num" => "328", "exponent" => "2",),
            "HKD" => array("Num" => "344", "exponent" => "2",),
            "HNL" => array("Num" => "340", "exponent" => "2",),
            "HRK" => array("Num" => "191", "exponent" => "2",),
            "HTG" => array("Num" => "332", "exponent" => "2",),
            "HUF" => array("Num" => "348", "exponent" => "2",),
            "IDR" => array("Num" => "360", "exponent" => "2",),
            "ILS" => array("Num" => "376", "exponent" => "2",),
            "INR" => array("Num" => "356", "exponent" => "2",),
            "IRR" => array("Num" => "364", "exponent" => "2",),
            "JMD" => array("Num" => "388", "exponent" => "2",),
            "KES" => array("Num" => "404", "exponent" => "2",),
            "KGS" => array("Num" => "417", "exponent" => "2",),
            "KHR" => array("Num" => "116", "exponent" => "2",),
            "KPW" => array("Num" => "408", "exponent" => "2",),
            "KYD" => array("Num" => "136", "exponent" => "2",),
            "KZT" => array("Num" => "398", "exponent" => "2",),
            "LAK" => array("Num" => "418", "exponent" => "2",),
            "LBP" => array("Num" => "422", "exponent" => "2",),
            "LKR" => array("Num" => "144", "exponent" => "2",),
            "LRD" => array("Num" => "430", "exponent" => "2",),
            "LSL" => array("Num" => "426", "exponent" => "2",),
            "MAD" => array("Num" => "504", "exponent" => "2",),
            "MDL" => array("Num" => "498", "exponent" => "2",),
            "MKD" => array("Num" => "807", "exponent" => "2",),
            "MMK" => array("Num" => "104", "exponent" => "2",),
            "MNT" => array("Num" => "496", "exponent" => "2",),
            "MOP" => array("Num" => "446", "exponent" => "2",),
            "MUR" => array("Num" => "480", "exponent" => "2",),
            "MVR" => array("Num" => "462", "exponent" => "2",),
            "MWK" => array("Num" => "454", "exponent" => "2",),
            "MXN" => array("Num" => "484", "exponent" => "2",),
            "MXV" => array("Num" => "979", "exponent" => "2",),
            "MYR" => array("Num" => "458", "exponent" => "2",),
            "MZN" => array("Num" => "943", "exponent" => "2",),
            "NAD" => array("Num" => "516", "exponent" => "2",),
            "NGN" => array("Num" => "566", "exponent" => "2",),
            "NIO" => array("Num" => "558", "exponent" => "2",),
            "NOK" => array("Num" => "578", "exponent" => "2",),
            "NPR" => array("Num" => "524", "exponent" => "2",),
            "NZD" => array("Num" => "554", "exponent" => "2",),
            "PAB" => array("Num" => "590", "exponent" => "2",),
            "PEN" => array("Num" => "604", "exponent" => "2",),
            "PGK" => array("Num" => "598", "exponent" => "2",),
            "PHP" => array("Num" => "608", "exponent" => "2",),
            "PKR" => array("Num" => "586", "exponent" => "2",),
            "PLN" => array("Num" => "985", "exponent" => "2",),
            "QAR" => array("Num" => "634", "exponent" => "2",),
            "RON" => array("Num" => "946", "exponent" => "2",),
            "RSD" => array("Num" => "941", "exponent" => "2",),
            "RUB" => array("Num" => "643", "exponent" => "2",),
            "SAR" => array("Num" => "682", "exponent" => "2",),
            "SBD" => array("Num" => "090", "exponent" => "2",),
            "SCR" => array("Num" => "690", "exponent" => "2",),
            "SDG" => array("Num" => "938", "exponent" => "2",),
            "SEK" => array("Num" => "752", "exponent" => "2",),
            "SGD" => array("Num" => "702", "exponent" => "2",),
            "SHP" => array("Num" => "654", "exponent" => "2",),
            "SLL" => array("Num" => "694", "exponent" => "2",),
            "SOS" => array("Num" => "706", "exponent" => "2",),
            "SRD" => array("Num" => "968", "exponent" => "2",),
            "SSP" => array("Num" => "728", "exponent" => "2",),
            "STD" => array("Num" => "678", "exponent" => "2",),
            "SVC" => array("Num" => "222", "exponent" => "2",),
            "SYP" => array("Num" => "760", "exponent" => "2",),
            "SZL" => array("Num" => "748", "exponent" => "2",),
            "THB" => array("Num" => "764", "exponent" => "2",),
            "TJS" => array("Num" => "972", "exponent" => "2",),
            "TMT" => array("Num" => "934", "exponent" => "2",),
            "TOP" => array("Num" => "776", "exponent" => "2",),
            "TRY" => array("Num" => "949", "exponent" => "2",),
            "TTD" => array("Num" => "780", "exponent" => "2",),
            "TWD" => array("Num" => "901", "exponent" => "2",),
            "TZS" => array("Num" => "834", "exponent" => "2",),
            "UAH" => array("Num" => "980", "exponent" => "2",),
            "USD" => array("Num" => "840", "exponent" => "2",),
            "USN" => array("Num" => "997", "exponent" => "2",),
            "UYU" => array("Num" => "858", "exponent" => "2",),
            "UZS" => array("Num" => "860", "exponent" => "2",),
            "VEF" => array("Num" => "937", "exponent" => "2",),
            "WST" => array("Num" => "882", "exponent" => "2",),
            "XCD" => array("Num" => "951", "exponent" => "2",),
            "YER" => array("Num" => "886", "exponent" => "2",),
            "ZAR" => array("Num" => "710", "exponent" => "2",),
            "ZMW" => array("Num" => "967", "exponent" => "2",),
            "ZWL" => array("Num" => "932", "exponent" => "2",),
            "MGA" => array("Num" => "969", "exponent" => "1",),
            "MRO" => array("Num" => "478", "exponent" => "1",),
            "BIF" => array("Num" => "108", "exponent" => "0",),
            "BYR" => array("Num" => "974", "exponent" => "0",),
            "CLP" => array("Num" => "152", "exponent" => "0",),
            "CVE" => array("Num" => "132", "exponent" => "0",),
            "DJF" => array("Num" => "262", "exponent" => "0",),
            "GNF" => array("Num" => "324", "exponent" => "0",),
            "ISK" => array("Num" => "352", "exponent" => "0",),
            "JPY" => array("Num" => "392", "exponent" => "0",),
            "KMF" => array("Num" => "174", "exponent" => "0",),
            "KRW" => array("Num" => "410", "exponent" => "0",),
            "PYG" => array("Num" => "600", "exponent" => "0",),
            "RWF" => array("Num" => "646", "exponent" => "0",),
            "UGX" => array("Num" => "800", "exponent" => "0",),
            "UYI" => array("Num" => "940", "exponent" => "0",),
            "VND" => array("Num" => "704", "exponent" => "0",),
            "VUV" => array("Num" => "548", "exponent" => "0",),
            "XAF" => array("Num" => "950", "exponent" => "0",),
            "XOF" => array("Num" => "952", "exponent" => "0",),
            "XPF" => array("Num" => "953", "exponent" => "0",),
        );
    }

    public function get_currency_exponent()
    {
        return array(
            "1" => "10",
            "2" => "100",
            "3" => "1000",
            "4" => "10000",
            "5" => "100000"
        );
    }
}